import * as CARRIERS from '@/data/keys/carrierKeys';
import * as SETTINGS from '@/data/keys/configKeys';

export const carrierPermissions = {
  [CARRIERS.POSTNL]: [
    SETTINGS.ALLOW_DELIVERY_OPTIONS,
    SETTINGS.ALLOW_EVENING_DELIVERY,
    SETTINGS.ALLOW_MONDAY_DELIVERY,
    SETTINGS.ALLOW_MORNING_DELIVERY,
    SETTINGS.ALLOW_ONLY_RECIPIENT,
    SETTINGS.ALLOW_PICKUP_EXPRESS,
    SETTINGS.ALLOW_PICKUP_LOCATIONS,
    SETTINGS.ALLOW_SIGNATURE,
    SETTINGS.PRICE_EVENING_DELIVERY,
    SETTINGS.PRICE_MONDAY_DELIVERY,
    SETTINGS.PRICE_MORNING_DELIVERY,
    SETTINGS.PRICE_ONLY_RECIPIENT,
    SETTINGS.PRICE_PICKUP,
    SETTINGS.PRICE_PICKUP_EXPRESS,
    SETTINGS.PRICE_SIGNATURE,
    SETTINGS.PRICE_STANDARD_DELIVERY,
  ],
  [CARRIERS.BPOST]: [
    SETTINGS.ALLOW_DELIVERY_OPTIONS,
    SETTINGS.ALLOW_ONLY_RECIPIENT,
    SETTINGS.ALLOW_PICKUP_LOCATIONS,
    SETTINGS.ALLOW_SATURDAY_DELIVERY,
    SETTINGS.ALLOW_SIGNATURE,
    SETTINGS.PRICE_ONLY_RECIPIENT,
    SETTINGS.PRICE_PICKUP,
    SETTINGS.PRICE_SATURDAY_DELIVERY,
    SETTINGS.PRICE_SIGNATURE,
    SETTINGS.PRICE_STANDARD_DELIVERY,
    SETTINGS.SATURDAY_CUTOFF_TIME,
  ],
  [CARRIERS.DPD]: [
    SETTINGS.ALLOW_DELIVERY_OPTIONS,
    SETTINGS.ALLOW_PICKUP_LOCATIONS,
    SETTINGS.PRICE_PICKUP,
    SETTINGS.PRICE_STANDARD_DELIVERY,
  ],
};
